### ISSUE TITLE
Error when running rails g active_admin:install User

### ISSUE THREAD

**Issue by aleksandarbasara** [cookieshq/hebillas#1]
Hey,

after running the suspenders with the hebillas template there is no active_admin installed. So when I install the active_admin, I get the following error.

Rails 4.2.0
Ruby 2.3.0

```
# rails g active_admin:install User
Running via Spring preloader in process 51
      invoke  devise
/usr/local/bundle/gems/activeadmin-1.0.0.pre2/lib/generators/active_admin/devise/devise_generator.rb:22:in `rescue in install_devise': You provided devise 4.1.1 but we need: ~> 3.2. If you don't want to use devise, run the generator with --skip-users. (ActiveAdmin::GeneratorError)
    from /usr/local/bundle/gems/activeadmin-1.0.0.pre2/lib/generators/active_admin/devise/devise_generator.rb:19:in `install_devise'
```

**Comment by julitrows** [comment]
Thanks for the heads up! 

It seems that active_admin is not ready to support Devise 4.1 yet and it's stuck with branch 3 of Devise. [See this](https://github.com/activeadmin/activeadmin/issues/4416).

I've modified our template, so if you don't choose to install active_admin, it will work with latest devise. In case you want to use active_admin, it will use branch 3 of Devise.

The latest commit ( d027991bdb9751d664e26f14e0029ede0f4fd161 ) addresses this.

Let me know how it works for you.

**Comment by aleksandarbasara** [comment]
@jantequera I'm now using administrate. :)

**Comment by julitrows** [comment]
Well, thanks for the heads up for the issue anyway :D

**Comment by nicalpi** [comment]
@aleksandarbasara @jantequera sounds like a good idea to add Administrate as an option as well?

**Comment by julitrows** [comment]
@spyou I'd prefer to invest time in refining what we have and what we use, and take out items from the "future improvements" list, than adding things we don't normally use.

Anyway, if @aleksandarbasara would like to send in a PR with Administrate I'd be more than happy to put it in if it's all right :)
